# docker compose file for running a 3-node PostgreSQL cluster
# with 3-node etcd cluster as the DCS and one haproxy node
version: "2"

# networks:
#     demo:

services:
    etcd3:
        image: patroni
        # networks: [ demo ]
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: etcd1=http://${IP_NODE_1}:2380,etcd2=http://${IP_NODE_2}:2380,etcd3=http://${IP_NODE_3}:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: tutorial
            DOCKER_IP: ${IP_NODE_3}
        container_name: etcd3
        ports:
            - "2379:2379"
            - "2380:2380"
        hostname: etcd3
        command: etcd -name etcd3 -initial-advertise-peer-urls http://${IP_NODE_3}:2380

    haproxy3:
        image: patroni
        # networks: [ demo ]
        env_file: docker/patroni.env
        hostname: haproxy3
        container_name: haproxy3
        ports:
            - "5000:5000"
            - "5001:5001"
            - "7000:7000"
        command: haproxy
        environment: &haproxy_env
            ETCDCTL_ENDPOINTS: http://${IP_NODE_1}:2379,http://${IP_NODE_2}:2379,http://${IP_NODE_3}:2379
            PATRONI_ETCD3_HOSTS: "'${IP_NODE_1}:2379','${IP_NODE_2}:2379','${IP_NODE_3}:2379'"
            PATRONI_SCOPE: demo
            DOCKER_IP: ${IP_NODE_3}

    patroni3:
        image: patroni
        # networks: [ demo ]
        env_file: docker/patroni.env
        hostname: patroni3
        container_name: patroni3
        ports:
            - "5432:5432"
            - "5433:5433"
            - "5434:5434"
            - "8008:8008"
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni3

    adminer:
        image: adminer
        restart: always
        links:
        - 'patroni3:db'
        ports:
        - '10080:8080'