# docker compose file for running a 3-node PostgreSQL cluster
# with 3-node etcd cluster as the DCS and one haproxy node
version: "2"

# networks:
#     demo:

services:
    etcd3:
        image: patroni
        # networks: [ demo ]
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: etcd1=http://172.31.37.68:2380,etcd2=http://172.31.38.74:2380,etcd3=http://172.31.39.75:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: tutorial
        container_name: etcd3
        hostname: etcd3
        command: etcd -name etcd1 -initial-advertise-peer-urls http://172.31.39.75:2380 -advertise-client-urls http://172.31.39.75:2379

    haproxy3:
        image: patroni
        # networks: [ demo ]
        env_file: docker/patroni.env
        hostname: haproxy3
        container_name: haproxy3
        ports:
            - "5000:5000"
            - "5001:5001"
        command: haproxy
        environment: &haproxy_env
            ETCDCTL_ENDPOINTS: http://172.31.37.68:2379,http://172.31.38.74:2379,http://172.31.39.75:2379
            PATRONI_ETCD3_HOSTS: "'172.31.37.68:2379','172.31.38.74:2379','172.31.39.75:2379'"
            PATRONI_SCOPE: demo

    patroni3:
        image: patroni
        # networks: [ demo ]
        env_file: docker/patroni.env
        hostname: patroni3
        container_name: patroni3
        ports:
            - "5432:5432"
            - "5433:5433"
            - "5434:5434"
            - "8008:8008"
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni3
            DOCKER_IP: 172.31.39.75
